<<<<<<< HEAD
version: '3.8'
=======
version: '3'
>>>>>>> a37c67209eeb1de7244348d245bfc2dd0ae5016e
services:
  web:
    build: .
    command: bundle exec ruby app.rb -o 0.0.0.0
    ports:
      - 4567:4567
    volumes:
      - .:/app
